#!/usr/bin/env ruby

this_dir = File.dirname(__FILE__)

system "rcup -d #{this_dir} -x '#{this_dir}:README.md #{this_dir}:rcm-install'"

rc_name = case ENV['SHELL']
  when '/bin/zsh'
    File.expand_path('~/.zshrc')
  when '/bin/bash'
    File.expand_path('~/.bashrc')
  else
    File.expand_path('~/.bashrc')
  end

if !File.exist?(rc_name) || !(File.read(rc_name) =~ /\.shrc\.extend/)
  File.open(rc_name, "a+") do |f|
    f.write <<~EOF
      if [ -f ~/.shrc.extend ]; then
        . ~/.shrc.extend
      fi
    EOF
  end
end
